name = "spectrum"
version = "1.1.5"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2023-2025, Jason Christopherson"
description = "A modern Fortran signal analysis library."
homepage = "https://github.com/jchristopherson/spectrum"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror" }
fftpack = { git = "https://github.com/fortran-lang/fftpack" }
linalg = { git = "https://github.com/jchristopherson/linalg" }

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "spectrum_tests"
source-dir = "test"
main = "spectrum_tests.f90"
